spacer_dict:
  RTW554:
      spacer: GGGCACGGGCAGCTTGCCGG
      orientation: 3prime
  RTW555:
      spacer: GTCGCCCTCGAACTTCACCT
      orientation: 5prime
  RTW574:
      spacer: CTGATGGTCCATGTCTGTTACTC
      #spacer: 'CTCATTGTCTGTACCTGGTAGTC' #reverse
      #spacer: GAGTAACAGACATGGACCATCAG # reverse complement
      orientation: 5prime
  RTW572:
    spacer: GGAATCCCTTCTGCAGCACCTGG
    orientation: 3prime

codes:
  'B': !!set 
    {'C', 'G', 'T'}
  'D': !!set
    {'A', 'G', 'T'}
  'H': !!set
    {'A', 'C', 'T'}   
  'K': !!set
    {'G', 'T'}
  'M': !!set
    {'A', 'C'}
  'N': !!set
      {'A', 'C', 'G', 'T'}
  'R': !!set
    {'A', 'G'}
  'S': !!set
    {'C', 'G'}
  'V': !!set
    {'A', 'C', 'G'}
  'W': !!set
    {'A', 'T'}
  'Y': !!set
    {'C', 'T'}

bbmerge:
  - 'mix=f'
  - 'usejni=t'
  - 'nn=t'
  - 'cutoff=0.901041'
  - 'pfilter=1'

shot_cutoff: 0.25
histogram_bins: 100
min_target_frac: 0.25

logo_file_type: 'pdf' # ['svg,'eps', 'ps', 'png', 'jpeg', 'tiff']