
# Generated by Qodo Gen
import pandas as pd 
from tamipami.tpio import histogram_plot
import altair as alt


import pytest

class TestHistogramPlot:

    # Add cutoff line when valid cutoff value is provided
    def test_histogram_with_cutoff_line(self):
        df = pd.DataFrame({'zscore': [1.2, 2.3, 3.4, 4.5]})
        maxbins = 10
        cutoff = 2.5
    
        chart = histogram_plot(df, maxbins, cutoff)
    
        assert isinstance(chart, alt.LayerChart)
        assert len(chart.layer) == 2
        assert chart.layer[1].mark.type == 'rule'
        assert chart.layer[1].mark.color == 'red'