name: Publish Docker image to GitHub Container Registry

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags like v1.0.0
  workflow_dispatch:  # Add this for manual triggering
    inputs:
      version:
        description: 'Version to build'
        required: true
        default: 'test-1.0.0'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # ✅ Ensure full Git history and tags are available for setuptools_scm
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 🛠️ Set up QEMU for cross-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 🛠️ Set up Docker Buildx with advanced features
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
            image=moby/buildkit:v0.12.0
          buildkitd-flags: --allow-insecure-entitlement network.host

      # 🔐 Authenticate with GitHub Container Registry (moved up for registry cache)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 🏷️ Extract version tag from Git reference
      - name: Get tag name
        id: get_tag
        run: |
          VERSION_TAG="${GITHUB_REF#refs/tags/}"
          VERSION_CLEAN="${VERSION_TAG#v}"
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
          echo "VERSION_CLEAN=$VERSION_CLEAN" >> $GITHUB_ENV
          
      # 🐳 Build and push Docker image with optimized registry caching
      - name: Build and push tamipami image
        uses: docker/build-push-action@v6
        env:
          BUILDKIT_CONTEXT_KEEP_GIT_DIR: true  # Ensures .git is preserved for setuptools_scm
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/usda-ars-gbru/tamipami:${{ env.VERSION_CLEAN }}
            ghcr.io/usda-ars-gbru/tamipami:latest
          build-args: |
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=true
            BUILDKIT_INLINE_CACHE=1
          # Use registry cache instead of local cache for much better performance
          cache-from: |
            type=registry,ref=ghcr.io/usda-ars-gbru/tamipami:cache
            type=registry,ref=ghcr.io/usda-ars-gbru/tamipami:latest
          cache-to: type=registry,ref=ghcr.io/usda-ars-gbru/tamipami:cache,mode=max
          # Enable advanced BuildKit features for faster builds
          provenance: false
          sbom: false