name: publish docker image to GH repo

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository with all history and tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0     # Ensures full git history and tags are available for setuptools-scm

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
            
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get short SHA
        id: slug
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
  
      - name: Build and push tamipami image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/usda-ars-gbru/tamipami:sha-${{ env.SHORT_SHA }}
          build-args: |
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
