name: Publish Docker image to GitHub Container Registry

on:
  push:
    tags:
      - 'v*'  # Trigger only on version tags like v1.0.0
  workflow_dispatch:  # Enable manual triggering
    inputs:
      version:
        description: 'Version to build (e.g., test-1.0.0)'
        required: true
        default: 'test-1.0.0'
        type: string
      push_to_registry:
        description: 'Push to registry?'
        required: true
        default: true
        type: boolean
      platforms:
        description: 'Target platforms'
        required: true
        default: 'linux/amd64'
        type: choice
        options:
          - 'linux/amd64'
          - 'linux/amd64,linux/arm64'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # ✅ Ensure full Git history and tags are available for setuptools_scm
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 🛠️ Set up QEMU for cross-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 🛠️ Set up Docker Buildx with advanced features
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
            image=moby/buildkit:v0.12.0
          buildkitd-flags: --allow-insecure-entitlement network.host

      # 🔐 Authenticate with GitHub Container Registry (moved up for registry cache)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 🏷️ Extract version tag from Git reference or use manual input
      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # Manual trigger - use input version
            VERSION_TAG="${{ github.event.inputs.version }}"
            VERSION_CLEAN="${VERSION_TAG#v}"
            PUSH_TO_REGISTRY="${{ github.event.inputs.push_to_registry }}"
            PLATFORMS="${{ github.event.inputs.platforms }}"
            IS_RELEASE="false"
            echo "Manual trigger - Version: $VERSION_TAG, Push: $PUSH_TO_REGISTRY, Platforms: $PLATFORMS"
          else
            # Tag push - extract from GITHUB_REF
            VERSION_TAG="${GITHUB_REF#refs/tags/}"
            VERSION_CLEAN="${VERSION_TAG#v}"
            PUSH_TO_REGISTRY="true"
            PLATFORMS="linux/amd64,linux/arm64"
            IS_RELEASE="true"
            echo "Tag trigger - Version: $VERSION_TAG"
          fi
          
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
          echo "VERSION_CLEAN=$VERSION_CLEAN" >> $GITHUB_ENV
          echo "PUSH_TO_REGISTRY=$PUSH_TO_REGISTRY" >> $GITHUB_ENV
          echo "PLATFORMS=$PLATFORMS" >> $GITHUB_ENV
          echo "IS_RELEASE=$IS_RELEASE" >> $GITHUB_ENV
          
          echo "Final values:"
          echo "  VERSION_TAG: $VERSION_TAG"
          echo "  VERSION_CLEAN: $VERSION_CLEAN"
          echo "  PUSH_TO_REGISTRY: $PUSH_TO_REGISTRY"
          echo "  PLATFORMS: $PLATFORMS"
          echo "  IS_RELEASE: $IS_RELEASE"
          
      # 🐳 Build and push Docker image with optimized registry caching
      - name: Build and push tamipami image
        uses: docker/build-push-action@v6
        env:
          BUILDKIT_CONTEXT_KEEP_GIT_DIR: true  # Ensures .git is preserved for setuptools_scm
        with:
          context: .
          push: ${{ env.PUSH_TO_REGISTRY }}
          platforms: ${{ env.PLATFORMS }}
          tags: |
            ghcr.io/usda-ars-gbru/tamipami:${{ env.VERSION_CLEAN }}
            ${{ env.IS_RELEASE == 'true' && 'ghcr.io/usda-ars-gbru/tamipami:latest' || '' }}
          build-args: |
            BUILDKIT_CONTEXT_KEEP_GIT_DIR=true
            BUILDKIT_INLINE_CACHE=1
          # Use registry cache instead of local cache for much better performance
          cache-from: |
            type=registry,ref=ghcr.io/usda-ars-gbru/tamipami:cache
            type=registry,ref=ghcr.io/usda-ars-gbru/tamipami:latest
          cache-to: type=registry,ref=ghcr.io/usda-ars-gbru/tamipami:cache,mode=max
          # Enable advanced BuildKit features for faster builds
          provenance: false
          sbom: false

      # 🧪 Test the built image (optional step for manual runs)
      - name: Test Docker image
        if: github.event_name == 'workflow_dispatch' && env.PUSH_TO_REGISTRY == 'true'
        run: |
          echo "Testing the built Docker image..."
          docker run --rm ghcr.io/usda-ars-gbru/tamipami:${{ env.VERSION_CLEAN }} --help || echo "Image test completed"
